name: C/C++ CI

on:
  push:
    branches: [ "branchMake" ]
  pull_request:
    branches: [ "branchMake" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
    
    - name: set up gcc
      run: sudo apt-get install g++ 
    
    - name: build 
      run: make
      
    - name: run tests in any
      run: ./main
